### ISSUE TITLE
Category dropdown appears under SERP tool

### ISSUE THREAD

**Issue by notfalsedev** [ChristopherDosin/Shopware-6-Blog-Plugin#104]
The category dropdown is appearing under the SERP tool.
This way we can not select different categories.

![dropdown](https://i.ibb.co/j5X1kQh/Schermafbeelding-2022-05-06-om-11-08-51.png)

**Comment by ChristopherDosin** [comment]
@notfalsedev Thanks for the report: which Shopware and Blog Version Are you using?

**Comment by ChristopherDosin** [comment]
@viennt could you have a look at this?

**Comment by viennt** [comment]
@ChristopherDosin sure, I'll have a PR for this soon.

**Comment by ChristopherDosin** [comment]
@viennt Do we already fixed it somewhere? Kind reminder for this one.

**Comment by viennt** [comment]
@ChristopherDosin I've seen this bug before, but I can't reproduce it recently. Seem weird. Let me spend more time reproducing it.

**Comment by ChristopherDosin** [comment]
oki
