### ISSUE TITLE
Block is overwritten instead of added

### ISSUE THREAD

**Issue by TWentzler** [ChristopherDosin/Shopware-6-Blog-Plugin#113]
Hi christoph,

thanks a lot for the free plug-ing!

Unfortunately, we have a conflict with our theme as the plug-in is hard core overwriting theme block.

Would it be possible to change the code so that it is added instead of overwritten?

Our support wrote the following:

2. If a block is overwritten, this is not always necessary. A developer should therefore always check whether overwriting a block is absolutely necessary. If necessary, the code of the plugin can be rewritten so that no overwriting is necessary. Functions can often be activated or deactivated via a configuration. If a function is not used, the standard code of an overwritten block should be loaded, here is an example:

{% block layout_navigation_categories_item %}

{% if config('PluginName.config.element') %}

{# Overwrite block with new content #}

{% else %}

{# Load previous content of block #}

{{ parent() }}

{% endif %}

Waiting for your feedback.

Best
Tobias

**Comment by ChristopherDosin** [comment]
Hey, @TWentzler - can you show me an example where a block is overwritten?

**Comment by TWentzler** [comment]
Hi @ChristopherDosin ,

Thanks a lot for getting back!

My agency told me that our problem lies within the following code block:

"For overlay search:

The overlay search throws a javascript error that the close button for the overlay does not exist, see screenshot.
Shape & Shift's SasBlogModule plugin overwrites the {% block layout_header_search_input_group %} block in the /storefront/layout/header/search.html.twig file without inheriting any previous content. This causes the plugin to overwrite the previous code with its own. In this case, the plugin removes the close button of our overlay search.
„

Does this help you? As a general hint they wrote:

„
explanations:

Blocks are entry points in the theme's template files that developers and makers can use to add code or even overwrite entire sections. Overwriting a block should always be considered carefully, since previously loaded code from the Shopware core and the code of other plugins will be overwritten. This does not happen when adding code.



When overwriting, there is an order. Our theme comes before the plugins in the order of inheritance. This ensures that other plugins can overwrite our theme content, just like they could with the default theme. With this we give the maximum possible compatibility with other plugins by allowing other manufacturers to overwrite our code so that their extensions work.



Of course, plugins can also overwrite each other if they overwrite code on the same block. In this case, the last loaded plugin usually wins - possibly the last installed plugin.



Suggested solution:

If other plugins overwrite important functions of the theme, there are various possibilities:

1. Uninstall the plugin if not needed.

2. If a block is overwritten, this is not always necessary. A developer should therefore always check whether overwriting a block is absolutely necessary. If necessary, the code of the plugin can be rewritten so that no overwriting is necessary. Functions can often be activated or deactivated via a configuration. If a function is not used, the standard code of an overwritten block should be loaded, here is an example:



{% block layout_navigation_categories_item %}

{% if config('PluginName.config.element') %}

{# Overwrite block with new content #}

{% else %}

{# Load previous content of block #}

{{ parent() }}

{% endif %}

{% endblock %}
"

**Comment by ChristopherDosin** [comment]
@viennt Could you also have a look at this issue?
