### ISSUE TITLE
Menu entry not visible after shopware update

### ISSUE THREAD

**Issue by pegelf** [ChristopherDosin/Shopware-6-Blog-Plugin#114]
I've updated shopware to version 6.4.12 and now the menu entry for the blog is missing in the Shopware backend. When I hover over the "content" entry, there are just the three items that are provided by default.

In the "my extensions" section, the plugin is activated and I can still configure the plugin settings.

I've already tried uninstalling the plugin and installing it from the plugin store again, but that hasn't fixed the issue.

Do you have an idea what could cause that error?

**Comment by ChristopherDosin** [comment]
@viennt could you have a look at it?

**Comment by viennt** [comment]
Okay, let me reproduce it first, then fix it.

**Comment by viennt** [comment]
@pegelf I also can't reproduce the issue. Anyway, thank you for letting us know.
