### ISSUE TITLE
Configuration does not affect storefront

### ISSUE THREAD

**Issue by netzkombyse** [ChristopherDosin/Shopware-6-Blog-Plugin#115]
Hi Christoph,

as bespoken on Slack, here is my issue:

I configurate to show 8 posts on one page - but only 5 are shown.
I configure not to shop author and category - but both selectors are shown in the storefront.
And then randomly sone posts appear repeatetly on different pages.

Live-Example is here: https://premiumwheels.de/Service/Ratgeber/

Thanks a lot for your feedback.

<img width="1710" alt="Bildschirmfoto 2022-06-22 um 10 02 48" src="https://user-images.githubusercontent.com/10908978/176539054-73c4448d-1ad7-4f8f-a360-a3efc060ffa3.png">

<img width="1718" alt="Bildschirmfoto 2022-06-22 um 10 02 37" src="https://user-images.githubusercontent.com/10908978/176539049-f989fc92-1fd3-4d18-91c6-1a38d9182585.png">

**Comment by ChristopherDosin** [comment]
@netzkombyse Did you change the layout already within the category -> layout tab?
Could you try to do your changes within the category->layout tab?

Because as soon as you save something within category->layout this will override the settings and content from the actual CMS Designer.

**Comment by ChristopherDosin** [comment]
I will close this issue since we've already released version two.
