### ISSUE TITLE
Author is not shown in blog listing

### ISSUE THREAD

**Issue by nmontag** [ChristopherDosin/Shopware-6-Blog-Plugin#125]
The Author is not shown in the listing.

We just started using the Plugin, but the author of the blogs is not shown in the listing. On the example images in the Shopware Store the author is shown. We are currently on Shopware 6.4.8.2.

PS: Except this one issue, we are very happy with the plugin.

**Comment by ChristopherDosin** [comment]
@viennt could you have a look at it?

**Comment by ChristopherDosin** [comment]
@nmontag did you enable the "show author" option within the plugin settings?

![Bildschirmfoto 2022-10-31 um 16 23 50](https://user-images.githubusercontent.com/8193345/199030945-02f511e0-37fa-498b-8994-c46599dd880c.png)

**Comment by nmontag** [comment]
> @nmontag did you enable the "show author" option within the plugin settings?
> 
> ![Bildschirmfoto 2022-10-31 um 16 23 50](https://user-images.githubusercontent.com/8193345/199030945-02f511e0-37fa-498b-8994-c46599dd880c.png)

Yes, the option is enabled

**Comment by ChristopherDosin** [comment]
@pedramham Please also take a look at this issue.

**Comment by TimWuyts** [comment]
We're experiencing the same issue, this has been working initially. However after updating the plugin the aggregations for both categories & authors remain empty in blog-filter-panel.html.twig.

`{% set blogCategories = listing.aggregations.get('blogCategories') %}`

**Comment by TimWuyts** [comment]
I'm assuming this could be also related to [issue 115](https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/issues/115).

**Comment by ChristopherDosin** [comment]
@TimWuyts Got it - We'll look into this issue tomorrow.

**Comment by hungmac-sw** [comment]
It will be fixed after this [PR](https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/pull/142) is merged and released in the next version

**Comment by ChristopherDosin** [comment]
Fixed in https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/pull/142
