### ISSUE TITLE
Reopening "Custom fields" issue/request

### ISSUE THREAD

**Issue by Alphaegen** [ChristopherDosin/Shopware-6-Blog-Plugin#127]
**Original:**
https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/issues/119

I think this issue/request was overlooked, but I was wondering whether anyone kan give an update on it?

**Comment by ChristopherDosin** [comment]
Duplicate of https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/issues/119
