### ISSUE TITLE
Add share icons to blog detail view

### ISSUE THREAD

**Issue by noahmenzi** [ChristopherDosin/Shopware-6-Blog-Plugin#128]
Hey 👋🏽
It would be cool to have an option to enable share icons on the blog detail page. Something like this: 
<img width="138" alt="Screenshot 2022-12-04 at 18 44 58" src="https://user-images.githubusercontent.com/5870003/205506826-73f67e19-d693-46a6-8afa-1d40cc5b4e65.png">
Is this something you would consider adding to the plugin? We might have time to prepare a Pull request for it. 
Best, 
Noah

**Comment by ChristopherDosin** [comment]
Good Morning @noahmenzi - I am not really sure if this is still used in 2023. Personally i never ever used such share links in the storefront. Normally you just copy & paste the link manually somewhere.
