### ISSUE TITLE
BlogSubscriber not present in config.xml

### ISSUE THREAD

**Issue by FinnMcLaughlin-Knorke** [ChristopherDosin/Shopware-6-Blog-Plugin#138]
I installed the SW6 plugin yesterday, and was confused as to why the category / author filters were not present in the blog post listing page.

After doing some investigation in the plugin code, I found that the **BlogSubscriber** (_..Content\Blog\Subscriber\BlogSubscriber_) was not being called from the config.xml.

Is this something that you are aware is missing, and if so what is the new method of activating the post filters? If not, will this be amended soon?

**Comment by hungmac-sw** [comment]
@FinnMcLaughlin-Knorke Thank you for your report. This file should be in the services.xml. We will fix it within the next release
