### ISSUE TITLE
Error: Unknown feature FEATURE_SAS_BLOG_V2

### ISSUE THREAD

**Issue by klaeser** [ChristopherDosin/Shopware-6-Blog-Plugin#151]
After installing and activating the plugin version 1.5.11 at Shopware 6.4.18.0 with APP_ENV=dev, we get the error message:
"Unknown feature FEATURE_SAS_BLOG_V2"

It means that the feature flag has to be somehow registered in Shopware - but we don't know how this should be done.

We could work around this by creating a new file config/packages/features.yaml with the following content:

`shopware:
  feature:
    flags:
      - name: FEATURE_SAS_BLOG_V2
        default: false
        major: false
`

What would be the right solution for this problem?

**Comment by ChristopherDosin** [comment]
We're looking into the issue - Thanks for reporting.
