### ISSUE TITLE
Meta Title & Description not taken to main language

### ISSUE THREAD

**Issue by SeanMerger** [ChristopherDosin/Shopware-6-Blog-Plugin#154]
If the base language of the installation is different from the storefront language, there seems to be a problem with the SERPs.

Steps to reproduce:

- Shopware installation (6.4.19) with main language English 
- Shopware frontend in German
- Posts are written in the main language (English), since you cannot switch to German, before saving the post. The german translation is not touched.
- Posts are showing just finde in the german frontend, but Meta Title and Description are missing.
- German translation is edited (Title added - since required, SERPS added) -> Meta Title and Description showing

Does not belong into tickets, but: thank you @ChristopherDosin for this plugin! Much appreciated!

**Comment by ChristopherDosin** [comment]
@SeanMerger Thanks for reporting - We'll have a look into that issue.
