### ISSUE TITLE
Shopware 6.5 RC installation error

### ISSUE THREAD

**Issue by daslicht** [ChristopherDosin/Shopware-6-Blog-Plugin#156]
Hello,
I just tried to install teh Blog Module under shopware 6.5 rc.
When I start the installation I get :

```
Sas\BlogModule\Util\Lifecycle::__construct(): Argument #2 ($cmsPageRepository) must be of type Shopware\Core\Framework\DataAbstractionLayer\EntityRepositoryInterface, Shopware\Core\Framework\DataAbstractionLayer\EntityRepository given, called in /Users/daslicht/Sites/shopware-65-rc-dev/custom/plugins/Shopware-6-Blog-Plugin-1.5.14/src/SasBlogModule.php on line 272
```

**Comment by ChristopherDosin** [comment]
@daslicht The latest release is not compatible with 6.5 and will not be.
We will release a version 2 of the plugin that will be compatible with 6.5+

**Comment by ChristopherDosin** [comment]
@daslicht I will close this issue. You can follow me on LinkedIn for some latest updates.
We're currently making the latest changes for the version 2 release:

https://www.linkedin.com/in/christopher-dosin/
