### ISSUE TITLE
BlogCacheInvalidSubscriber calling non existant method

### ISSUE THREAD

**Issue by kingschnulli** [ChristopherDosin/Shopware-6-Blog-Plugin#157]
https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/blob/738ff2ef48e9aec5bdcdd60338031b8824218a67/src/Subscriber/BlogCacheInvalidSubscriber.php#L62

This will stop the admin from saving seo url templates, will throw the following exception:

`"Failed to create closure from callable: class Sas\\BlogModule\\Subscriber\\BlogCacheInvalidSubscriber does not have a method \"onUpdateCacheCategory\""`

**Comment by ChristopherDosin** [comment]
@kingschnulli Thanks for reporting. We'll look into this asap.
