### ISSUE TITLE
Can't see the blog menu on left side bar 

### ISSUE THREAD

**Issue by Ali-Ahmed-xixa** [ChristopherDosin/Shopware-6-Blog-Plugin#158]
I can't see the blog menu on left side bar 
my shopware version is 6.4.12.0
please someone help me.

**Comment by Ali-Ahmed-xixa** [comment]
![image](https://user-images.githubusercontent.com/55052400/225332481-2fce45c7-b1f2-428d-bc14-4b073676816d.png)
here is the screenshoot

**Comment by Pascualsolutions** [comment]
I have the same problem. Did you find the solution? Best regards Alex.

**Comment by ChristopherDosin** [comment]
@Pascualsolutions Which Shopware version and plugin version?

Anything within the browser console that throws an error or within the network tab?

**Comment by Pascualsolutions** [comment]
No error in console, in shopping expirience i see blog template but cant find in admin.

**Comment by Pascualsolutions** [comment]
> @Pascualsolutions Which Shopware version and plugin version?
Shopware version 6.5.5.1 and plugin version is 2.0.3
> 
> Anything within the browser console that throws an error or within the network tab?
No error code in console

**Comment by ChristopherDosin** [comment]
I will close this issue, since it's likely more related to a server config and maybe the plugin wasn't installed via the store ( so it needs to be manually compiled if not installed via the store ).
