### ISSUE TITLE
SEO-settings: error on save

### ISSUE THREAD

**Issue by Dead-Man-Walker** [ChristopherDosin/Shopware-6-Blog-Plugin#163]
Saving the SEO-settings fails due to a server error thrown by this plugin:

_Failed to create closure from callable: class 'Sas\BlogModule\Subscriber\BlogCacheInvalidSubscriber' does not have a method 'onUpdateCacheCategory'_

![image](https://user-images.githubusercontent.com/11764115/229512091-4347e86d-8454-44ba-a88f-35b621b095dd.png)

**Comment by despokd** [comment]
+1

**Comment by ChristopherDosin** [comment]
Should be solved within https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/commit/de29dce1eaa6932a5db881ab513aa6dbb4f4b183

**Comment by ChristopherDosin** [comment]
I will close this ticket, if it still appears please open a new issue.
