### ISSUE TITLE
SW 6.5 Internal Server Error on activation

### ISSUE THREAD

**Issue by seabokas** [ChristopherDosin/Shopware-6-Blog-Plugin#166]
Error: Class Sas\BlogModule\Content\BlogCategory\BlogCategoryIndexer contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Shopware\Core\Framework\DataAbstractionLayer\Indexing\EntityIndexer::getTotal, Shopware\Core\Framework\DataAbstractionLayer\Indexing\EntityIndexer::getDecorated

SW Version 6.5.0.0
Plugin Version 1.5.14

**Comment by ChristopherDosin** [comment]
The plugin is not ready yet for Shopware 6.5
We're working currently on a version 2 that is compatible with Shopware 6.5

However: Version 2 will have no backwards compability and version 1 will not supported 6.5 We'll make a hard cut here, since version 2 and SW 6.5 has a lot of changes.

**Comment by revoltek-daniel** [comment]
is there any eta for the 6.5 version?

**Comment by Tim-VL** [comment]
Any updates on 6.5?
Thanks!

**Comment by rvzug** [comment]
Any updates on 6.5?
Thanks!

**Comment by ChristopherDosin** [comment]
We'll be able to finish it this month i guess.

**Comment by rvzug** [comment]
Nice would be great!

**Comment by ChristopherDosin** [comment]
I will close this ticket, since version 2 was released for Shopware 6.5
