### ISSUE TITLE
Format of Date

### ISSUE THREAD

**Issue by meugster** [ChristopherDosin/Shopware-6-Blog-Plugin#17]
Currently, the date format of a blog post being used looks like that:
<img width="282" alt="Bildschirmfoto 2020-10-15 um 14 05 32" src="https://user-images.githubusercontent.com/4046860/96120879-7f42f800-0eef-11eb-8c55-151a2935f2a7.png">

Can this format be changed e.g. to DD.MM.YYYY hh:ss?

**Comment by ChristopherDosin** [comment]
The format can be easily changed if you overwrite the specific date block which you can find here 

-> https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/blob/master/src/Resources/views/storefront/component/blog/card/box.html.twig#L46

So your template would look like this:

```
{% sw_extends '@SasBlogModule/storefront/component/blog/card/box.html.twig' %}

{% block sas_blog_card_title_date %}
    <small>{{ article.createdAt|date(" DD.MM.YYYY hh:ss") }}</small>
{% endblock %}
```

For the blog detail page you would have this template:
https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/blob/master/src/Resources/views/storefront/element/cms-element-blog-detail.html.twig#L11-L15

```
{% sw_extends '@SasBlogModule/storefront/element/cms-element-blog-detail.html.twig' %}

{% block page_product_detail_review_item_info_date %}
    <div class="col-12 sas-blog-detail-item-date">
        <p><small>{{ element.data.createdAt|date((" DD.MM.YYYY hh:ss") }}</small></p>
    </div>
{% endblock %}
```
