### ISSUE TITLE
Dont see Blog create in admin panel

### ISSUE THREAD

**Issue by Pascualsolutions** [ChristopherDosin/Shopware-6-Blog-Plugin#184]
Dear, in version 6.5.5.1 i dont see Blog secrion in content admin panel. Is this bag or maby i do something wrong.
Best regards, Alex.
![Screenshot from 2023-09-16 13-31-18](https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/assets/75854186/702f5cd3-722f-47ad-a193-abeb2f458431)

**Comment by noxsii** [comment]
@Pascualsolutions I have now tested the whole thing and there is probably a problem with the 6.5.5.1. Will put that times after

**Comment by noxsii** [comment]
@Pascualsolutions pls run `./build-administration.sh` in the CLI. It then works :)

**Comment by Pascualsolutions** [comment]
Thank you :) i will check this soon. Best regards

**Comment by noxsii** [comment]
@niklasnx pls clean the cache from browser after build!

**Comment by niklasnx** [comment]
Unfortunately still not working, even after clearing browser cache. I installed the plugin from GitHub and i also use the version 6.5.5.1.

**Comment by TWentzler** [comment]
Same for me. build-administration.sh and clear cache did not solve the problem. Where do I find /to/blog/src/Resources/app/administration ?

**Comment by TWentzler** [comment]
@patrickleo175 thx for your support. I ran `npm i` and it told me that the version is too low, but then after 2nd trial it said `up to date, audited 2 packages in 323ms `
For `bin/build-administration.sh` in the administration folder, I received the following message:
```
web/shopware6/custom/plugins/SasBlogModule/src/Resources/app/administration$ bin/build-administration.sh
bash: bin/build-administration.sh: No such file or directory
```

also tried ./build-administration.sh

this is the npm version
{
  administration: '1.0.0',
  npm: '8.19.4',
  node: '16.20.2',
  v8: '9.4.146.26-node.26',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.19.1',
  modules: '93',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.11',
  openssl: '1.1.1v+quic',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022f',
  unicode: '14.0',
  ngtcp2: '0.8.1',
  nghttp3: '0.7.0'

**Comment by ChristopherDosin** [comment]
I will close this ticket, since it's not really related to the plugin and rather a server configuration. Feel free to re-open the issue if you have any problems.
