### ISSUE TITLE
sizing mode of section won't work properly

### ISSUE THREAD

**Issue by Oliverhorn** [ChristopherDosin/Shopware-6-Blog-Plugin#185]
as a user, i expect, that when i set the sizing mode of a section to full width instead of boxed content, the section is full width.
But even after cleaning the cache, the size is still boxed content.

**Comment by ChristopherDosin** [comment]
This should be fixed within https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/pull/207 
Right, @patrickleo175 ?

**Comment by ChristopherDosin** [comment]
I will close this ticket, Issue is fixed within https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/pull/207 and the `2.0.8` release.
