### ISSUE TITLE
is this extension compatible with 6.5.6.1?

### ISSUE THREAD

**Issue by MyNameIsAlaa** [ChristopherDosin/Shopware-6-Blog-Plugin#198]
hello, 

i'm trying to use this extension with shopware 6.5.6.1, however after install i don't see the entity under content > blog

**Comment by ChristopherDosin** [comment]
We'll have a look at this.

**Comment by ChristopherDosin** [comment]
Did you installed the plugin from the GitHub repo? If so: did you also build the admin after?

**Comment by MyNameIsAlaa** [comment]
hi @ChristopherDosin  thanks for your reply i really appreciate it,Yes i installed the plugin from this repo and didn't build the admin, how i do that?

**Comment by patrickleo175** [comment]
@MyNameIsAlaa could you please run this command line at your root Shopware platform? 


```sh
 composer build:js 
```

**Comment by MyNameIsAlaa** [comment]
@patrickleo175   i got this error  ` There are no commands defined in the "build" namespace.`

**Comment by TWentzler** [comment]
@patrickleo175  trying this here to solve the problem from #184 issue ... I receive the same error as @MyNameIsAlaa ... running the command like this "...45:/ web/shopware6$ composer build:js"

**Comment by MyNameIsAlaa** [comment]
my composer.json seem a lot shorter, i'm not sure why

**Comment by MyNameIsAlaa** [comment]
@patrickleo175  this is my composer.json 

```
{
    "name": "shopware/production",
    "license": "MIT",
    "type": "project",
    "require": {
        "composer-runtime-api": "^2.0",
        "shopware/administration": "6.5.7.2",
        "shopware/core": "6.5.7.2",
        "shopware/elasticsearch": "6.5.7.2",
        "shopware/storefront": "6.5.7.2",
        "symfony/flex": "~2",
        "symfony/runtime": "^5.0|^6.0"
    },
    "repositories": [
        {
            "type": "path",
            "url": "custom/plugins/*",
            "options": {
                "symlink": true
            }
        },
        {
            "type": "path",
            "url": "custom/plugins/*/packages/*",
            "options": {
                "symlink": true
            }
        },
        {
            "type": "path",
            "url": "custom/static-plugins/*",
            "options": {
                "symlink": true
            }
        }
    ],
    "prefer-stable": true,
    "config": {
        "allow-plugins": {
            "symfony/flex": true,
            "symfony/runtime": true
        },
        "optimize-autoloader": true,
        "sort-packages": true
    },
    "scripts": {
        "auto-scripts": {
            "assets:install": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "extra": {
        "symfony": {
            "allow-contrib": true,
            "endpoint": [
                "https://raw.githubusercontent.com/shopware/recipes/flex/main/index.json",
                "flex://defaults"
            ]
        }
    }
}

```

**Comment by MyNameIsAlaa** [comment]
Hey @patrickleo175 i have tried that command, my server cpu went 100% all day and i had to restart the server,

**Comment by ChristopherDosin** [comment]
@MyNameIsAlaa The build command from Shopware is quite heavy. So running the npm install might take a lot of server resources. This has nothing to do specificlly with the blog plugin itself.

However: If you've installed the plugin via the store, or downloaded the [zip file from the release page](https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/releases/tag/2.0.7) on GitHub there should be no need to compile it, since the required files should already be there.

**Comment by ChristopherDosin** [comment]
I will close this ticket since it's not actually related directly to the plugin. We tested the plugin on `6.5.6.1` and it's working without any issues.

Make sure to install the plugin via the shopware store also.
