### ISSUE TITLE
Blog Plugin kills all meta-Infos from all other pages

### ISSUE THREAD

**Issue by dsiekiera** [ChristopherDosin/Shopware-6-Blog-Plugin#20]
If the blog plugin is active, all meta information of all other pages of the shop will be overwritten with "empty".

**Comment by ChristopherDosin** [comment]
@dsiekiera Thanks for reporting, i will have a look at it.

**Comment by dsiekiera** [comment]
@runelaenen, @ChristopherDosin  thx for quick fix.
