### ISSUE TITLE
Issue during the save operation of a sales channel when there are no blog entries present.

### ISSUE THREAD

**Issue by dawidkozlowski** [ChristopherDosin/Shopware-6-Blog-Plugin#200]
https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/blob/41fc116134ab657dc6198fcdb8045181d2aed11f/src/Storefront/Framework/Seo/SeoUrlRoute/SeoUrlUpdateListener.php#L70

In the BlogModule, there is a listener at `\Sas\BlogModule\Storefront\Framework\Seo\SeoUrlRoute\SeoUrlUpdateListener::onCreateNewSalesChannel` that triggers during the save process of a sales channel in order to generate SEO URLs for blog posts. If there are no blog entries, an empty array `$ids = []` is passed to `\Shopware\Core\Content\Seo\SeoUrlUpdater::update`. This empty array is then forwarded to `\Shopware\Core\Content\Seo\SeoUrlGenerator::generate`. In this method, a Criteria object is created using the empty array, which results in a `RuntimeException` at `vendor/shopware/core/Framework/DataAbstractionLayer/Search/Criteria.php:133`.

As a result of the aforementioned issue, payment methods are not being correctly saved in the `payment_method_ids` column of the `sales_channel` table. This leads to a situation where it's impossible to select payment methods at checkout which have not been saved in that column.

**Comment by patrickleo175** [comment]
Thank you so much. We are working on it :)

**Comment by ChristopherDosin** [comment]
I will close this issue since it's merged. Feel free to re-open it when you have any issues.
