### ISSUE TITLE
Blog listing: filter and pagination didn't work on landing page

### ISSUE THREAD

**Issue by fsshopmacher** [ChristopherDosin/Shopware-6-Blog-Plugin#201]
**Steps to reproduce:**
- Add "blog listing" element to cms layout
- Add layout to landing page and category
- Try to filter or paginate on both sites

**Current:**
- Category page: Filter and pagination works
- Landing page: Filter and pagination gets a console error:
`Value is not a valid UUID: `
![error](https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/assets/4737201/5681f30f-8a5d-44d4-ab8e-f4a2aaea0b94)

**Expectation:**
- Filter and pagination works on both sites

Shopware Version 6.5.6.0

**Comment by patrickleo175** [comment]
Hi thank you, we are working on it :)

**Comment by ChristopherDosin** [comment]
I will close this issue since it's merged. Feel free to re-open it when you have any issues.

**Comment by fsshopmacher** [comment]
Unfortunately the problem still exists. 

Can you please re-open the task? I don't have permission to do this, thank you!

**Comment by silverDuy** [comment]
Hi @fsshopmacher . It was fixed by this PR https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/pull/204 


I will close this issue since it's merged. Feel free to re-open it when you have any issues.
