### ISSUE TITLE
Blog entries are not updated

### ISSUE THREAD

**Issue by philippnies** [ChristopherDosin/Shopware-6-Blog-Plugin#205]
We currently have the problem that blog entries are not updated when the CMS page is saved.

The new texts are saved in the CMS slots, but not in sas_blog_entries_translation.

Can you please tell me which class is executed when saving the CMS page to save the changes.

I am using version 2.0.5 with SW 6.5.6.1

**Comment by ChristopherDosin** [comment]
Thanks for the report.
Quick question: Do they appear, after you [cleared the cache](https://docs.shopware.com/en/shopware-6-en/configuration/caches-indexes)?

**Comment by philippnies** [comment]
No, deleting the cache does not help.

Since the new texts are not transferred to sas_blog_entries_translation, I suspect a problem when saving.

Just as an info: the queues are not running for us, as we write posts on the test system. But this has had no effect in the past.

**Comment by ChristopherDosin** [comment]
Ah, sorry - Missed that one.
Could you maybe record a quick video for us? Or maybe even send us your admin credentials to hello@shapeandshift.dev so we can take a look also at your stage env?

**Comment by philippnies** [comment]
E-mail to you is on its way

**Comment by philippnies** [comment]
@patrickleo175 The response also does not contain the previously saved changes.

The row in sas_blog_entrie must be updated somewhere when a CMS page is saved. 
If you can tell me where this takes place, I can debug the problem myself.

**Comment by philippnies** [comment]
We have found the error.

We have read element.data.translated.content using a theme override. With an older update, you added a check 
`{% if not element.data.cmsPage %}`
 which was not present in our source code.
