### ISSUE TITLE
Change LICENSE

### ISSUE THREAD

**Issue by runelaenen** [ChristopherDosin/Shopware-6-Blog-Plugin#25]
Hi @ChristopherDosin 
Can you please add a LICENSE file and update the license field accordingly in composer.json?
I think the MIT licence is a good fit for open source Shopware 6 plugins, as Shopware 6 itself uses it too and gives a lot of freedom to users and contributors.

**Comment by ChristopherDosin** [comment]
@runelaenen Sure, just fixed the license. No license file needed though in my opinion 😆
