### ISSUE TITLE
Symfony Exception

### ISSUE THREAD

**Issue by Ciatronical** [ChristopherDosin/Shopware-6-Blog-Plugin#50]
Hey,
nach dem Shopware-Update auf 6.4.0 erhalte ich folgende Fehlermeldung

"Sas\BlogModule\Controller\BlogController" has no container set, did you forget to define it as a service subscriber?
Log:
Uncaught PHP Exception LogicException: ""Sas\BlogModule\Controller\BlogController" has no container set, did you forget to define it as a service subscriber?" at /var/www/clients/client1/web36/web/vendor/symfony/framework-bundle/Controller/ControllerResolver.php line 39
{
    "exception": {}
}

Vielen Dank

**Comment by ChristopherDosin** [comment]
Das Plugin ist aktuell noch nicht fuer 6.4 freigegeben. Wir arbeiten aktuell an der 6.4 Kompatibilität.

**Comment by Ciatronical** [comment]
Ist abzusehen wann es fertig wird?
