### ISSUE TITLE
Blog-Kategorien (Backend) & Blogartikel (Frontend) nicht sichtbar

### ISSUE THREAD

**Issue by Barrington77** [ChristopherDosin/Shopware-6-Blog-Plugin#51]
![gfgfghfgh](https://user-images.githubusercontent.com/83944034/117619419-883b3580-b16f-11eb-8114-228d90988b0e.jpg)

Moin zusammen, wir haben dieses Plugin installiert und es scheint echt top zu sein, leider sehen wir im Backend unter "Inhalte > Blog" den Kategorie-Baum nicht (sehe Bild). Im Frontend ist das Listing der Blogartikel zu sehen, aber sobald wir versuchen, einen Blogartikel aufzurufen, bekommen wir die Fehlmeldung "Leider ist etwas schief gelaufen" und sehen den Artikel nicht.

Hat jemand eine Idee, was wir hierfalsch machen?

VG, Barrie

**Comment by ChristopherDosin** [comment]
@Barrington77 Welche Shopware Version habt Ihr im Einsatz?
Ich sehe das Ihr keine Blog Kategorien erstellt habt. Du muesstest dort eine Blog Kategorie anlegen und dann auch den Blog Artikel einer Kategorie zuweisen.

**Comment by Barrington77** [comment]
Hi Christopher, wir haben die neuste Version von Shopware, sind aber noch in der Testphase und migrieren das Ganze noch.

Blog-Kategorien hatten ich eigentlich angelegt, sind aber unter Inhalte > Blog nicht sichtbar:

![trrzu](https://user-images.githubusercontent.com/83944034/117961483-764bc500-b31e-11eb-94f0-27ef343cddf2.jpg)

aber wenn ich einen Blogartikel erstelle, sind die (teilweise gedoppelt, da ich nicht sicher war, ob die richtig angelegt worden waren) als Dropdown zu sehen:

![gfghfhgf](https://user-images.githubusercontent.com/83944034/117961527-81065a00-b31e-11eb-96b8-f5d59b3023c8.jpg)

 falls Du eine Idee hast, wären wir super dankbar!

**Comment by leduc92** [comment]
hi @Barrington77 I have created a merge request https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/pull/52, your issue can be fixed.

**Comment by ChristopherDosin** [comment]
We are working on the 6.4 compability as @leduc92 mentioned. So stay tuned for the update and see if this fixes your issue.

**Comment by Barrington77** [comment]
Super, vielen Dank.

**Comment by ChristopherDosin** [comment]
@Barrington77 We just released version 1.4 for Shopware 6.4

**Comment by Barrington77** [comment]
Moin Christopher, leider haben wir das Problem immer noch, dass die Blogartikel (Detailseiten) im Frontend nicht angezeigt werden. Ich glaube, dass das mit den Kategorien zusammenhängt, da diese im Backend nicht zu sehen sind. Sobald ich Kategorien im Backend unter "Inhalte > Blog >Blog Kategorien" erstelle, verschwinden die wieder (obwohl die auswählbar beim Erstellen von Blogartikeln sind). Ich verstehe nicht, woran das Problem liegen könnte...

Viele Grüße im Voraus.
Barrie
