### ISSUE TITLE
Cant show all blog on Shopware 6.4.*

### ISSUE THREAD

**Issue by HendyIvan** [ChristopherDosin/Shopware-6-Blog-Plugin#53]
Hello, Chris after install your module I can't show all blogs like your preview in-store shopware under **domain/blog** but when I use **domain/blog/detail name blog** it's working, can you tell me how can I solve this issue? 
this error when i just use **domain/blog** is 
![image](https://user-images.githubusercontent.com/9525991/122184332-50ce5000-ceb6-11eb-9a60-6556bae2e055.png)

**Comment by HendyIvan** [comment]
when using **domain/blog/detailnameblog** its working
![image](https://user-images.githubusercontent.com/9525991/122184659-a3a80780-ceb6-11eb-90f8-88f3af8d102f.png)

**Comment by HendyIvan** [comment]
hello @ChristopherDosin @runelaenen can you give suggestion for this issue

**Comment by ChristopherDosin** [comment]
@HendyIvan You have to create a category by your own and then assign the Blog Listing CMS page which is created during the plugin installation to your category.

There is no hardcoded `blog` URL.

If you still having troubles feel free to re-open the issue.
