### ISSUE TITLE
@Barrington77 We just released version 1.4 for Shopware 6.4

### ISSUE THREAD

**Issue by Barrington77** [ChristopherDosin/Shopware-6-Blog-Plugin#54]
Moin Christopher, leider haben wir das Problem immer noch, dass die Blogartikel (Detailseiten) im Frontend nicht angezeigt werden. Ich glaube, dass das mit den Kategorien zusammenhängt, da diese im Backend nicht zu sehen sind. Sobald ich Kategorien im Backend unter "Inhalte > Blog >Blog Kategorien" erstelle, verschwinden die wieder (obwohl die auswählbar beim Erstellen von Blogartikeln sind). Ich verstehe nicht, woran das Problem liegen könnte...

Viele Grüße im Voraus.
Barrie

**Comment by ChristopherDosin** [comment]
Hey @Barrington77,

sorry - Ich habe das Issue nicht auf dem Schirm gehabt. Besteht das Problem weiterhin?
Ansonsten sende mir gerne einmal die Zugangsdaten zum admin an christopher@shapeandshift.dev, sodass wir uns das direkt live einmal ansehen koennen.

**Comment by Barrington77** [comment]
Moin Christopher,

ich hatte Dir per E-Mail mit Zugangsdaten geantwortet, hab aber bisher keine Antwort erhalten. Die Zugangsdaten werde ich bald ändern, da ich nicht weiß, ob die bekommen hast oder nicht...eine kurze Rückmeldung wäre top. :)

**Comment by Barrington77** [comment]
@ChristopherDosin (falls die letzte Info nicht angekommen ist)

**Comment by ChristopherDosin** [comment]
@Barrington77 Kannst du mir noch einmal einen Ping senden per Mail?
Irgendwie bekomme ich bei GitHub keine Notification - muss ich einmal checken, sorry.

**Comment by Barrington77** [comment]
@ChristopherDosin ich habe jetzt 2 x unsere Zugangsdaten per E-Mail geschickt - sind die gut angekommen?

**Comment by ChristopherDosin** [comment]
@Barrington77 Hat sich das Problem mit dem neuen Update behoben?
