### ISSUE TITLE
wrong image resizing

### ISSUE THREAD

**Issue by pascaltippelt** [ChristopherDosin/Shopware-6-Blog-Plugin#56]
//english below

Hallo!

Wir nutzen dein Plugin und haben ein Problem mit dem resizing von Artikel-Bilder in der Artikel-Übersicht. Wird ein Fenster mit dem Blog in der Breite geändert, nachdem es geladen wurde, so werden die Bilder unnatürlich breit gezogen.

**Urzustand nach dem ersten Laden der Seite:**
![urzustand](https://i.ibb.co/Jpnk0d7/urzustand.png)
**rechtes Bild ändert sich beim Fenster resizen**
![Fenster verschoben](https://i.ibb.co/n0k7vrL/resized.png)

**Hier ein Video des Problems:**
https://youtu.be/5pWJeSq3HK4

Der einzige Unterschied, welcher mir auffällt zwischen Bildern die korrekt resized werden und jenen, bei denen es nicht klappt, ist die Auflösung. Probleme gibt es in meinem Fall bei Bildern mit 1920x1080, keine Probleme bei 800x600 (Stichprobe). Alles jpeg.

Ich hoffe dafür können wir eine Lösung finden.

Danke!

Hello!

We are using your plugin and have a problem with resizing article images in the article overview. If a window with the blog is changed in width after it has been loaded, the images will be drawn unnaturally wide.

** Original state after the first loading of the page: **
![urzustand](https://i.ibb.co/Jpnk0d7/urzustand.png)
** right picture changes when resizing window **
![Window moved](https://i.ibb.co/n0k7vrL/resized.png)

** Here is a video of the problem: **
https://youtu.be/5pWJeSq3HK4

The only difference I notice between images that are correctly resized and those that don't work is the resolution. In my case there are problems with images with 1920x1080, no problems with 800x600 (sample). Everything in jpeg.

I hope we can find a solution for that.

Thanks!

**Comment by ChristopherDosin** [comment]
@pascaltippelt Sorry for the late reply. I finally enabled my notifications 👍 
we will look into this issue soon.

@pedramham Please take a look also at this issue.

**Comment by pedramham** [comment]
> //english below
> 
> We are using your plugin and have a problem with resizing article images in the article overview. If a window with the blog is changed in width after it has been loaded, the images will be drawn unnaturally wide.

Hi @pascaltippelt , I uploaded an image with **1920x1080** size for an article.i didn't have your problem.Are you using a theme plugin?
https://www.youtube.com/watch?v=-6qkujMNWEE

**Comment by ChristopherDosin** [comment]
I will close this issue for inactivity.
