### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by ReinhardSchmidbauer** [ChristopherDosin/Shopware-6-Blog-Plugin#73]
As a shop admin and avid user of your blog plugin for shopware 6, I'd love to be able to create an RSS feed for my blog so that I can use the content of my blog posts in my e-mail newsletter and social media marketing efforts more effectively.

**Comment by ChristopherDosin** [comment]
Hi @ReinhardSchmidbauer sorry for the very late reply.
We will tackle this soon.
