### ISSUE TITLE
Pre-view cut off (custom theme)

### ISSUE THREAD

**Issue by TWentzler** [ChristopherDosin/Shopware-6-Blog-Plugin#74]
Hi,

we are using a custom theme by Zenit design and experiencing a cut off from the pre-view text. Maybe someone could point us in a direction how to solve the issue.

<img width="1221" alt="Custom theme - cut off" src="https://user-images.githubusercontent.com/93056492/138570584-0682c60a-c7ca-428d-b09e-5fd4d21791a7.png">

<img width="1090" alt="Standard theme - OK" src="https://user-images.githubusercontent.com/93056492/138570588-8f2b7555-65ea-4168-a7d8-3ae18020bd13.png">

Thanks,
Tobias

**Comment by ChristopherDosin** [comment]
Hey @TWentzler - Without having an URL to inspect it we can't help. Feel free to re-open the comment if you can post the URL.
