### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by cirellamhcs** [ChristopherDosin/Shopware-6-Blog-Plugin#75]
# Description

The single blog pages are not listed in the sitemap.

# Question

Did I misconfigure the extension?

**Comment by ChristopherDosin** [comment]
@cirellamhcs We'll tackle this issue.

**Comment by krasepixup** [comment]
We are having the Issue, despite running the plugin in the latest Version 1.5.7.  I am getting the following error-message when running bin/console sitemap:generate

`12:11:40 CRITICAL  [console] Error thrown while running command "sitemap:generate -f". Message: "Return value of Shopware\Core\Content\Sitemap\Struct\Url::getLoc() must be of the type string, null returned" ["exception" => TypeError { …},"command" => "sitemap:generate -f","message" => "Return value of Shopware\Core\Content\Sitemap\Struct\Url::getLoc() must be of the type string, null returned"]

In Url.php line 63:
                                                                                                                
  Return value of Shopware\Core\Content\Sitemap\Struct\Url::getLoc() must be of the type string, null returned  
                                                                                                                

sitemap:generate [-i|--salesChannelId [SALESCHANNELID]] [-f|--force]
`
Disabling the Plugin fixed the Problem.

The Shopware-Version is v6.4.6.1

**Comment by claymore008** [comment]
We have the same issue. We have 7 sales channels and they could'nt be generated with the same error as above (screenshot attached)

After disabling, generation is immediatelly done!

Plugin: 1.5.7 and SW Version: 6.4.17.2

So please fix it!

**Comment by ChristopherDosin** [comment]
I've reopened this issue and we'll take a look at it this week.

**Comment by hungmac-sw** [comment]
I closed this issue because we fixed it from [1.5.10](https://github.com/ChristopherDosin/Shopware-6-Blog-Plugin/releases/tag/1.5.10)
