### ISSUE TITLE
Blog-Article design

### ISSUE THREAD

**Issue by CMS-F** [ChristopherDosin/Shopware-6-Blog-Plugin#92]
Hi,
one more thing ;-)
it would be nice if you could make the blog articles a little better to design. Maybe even something like the "erlebniswelten". 

Hallo,
es wäre schön, wenn man die Blog-Artikel etwas besser gestalten könnte. Eventuell wie die Erlebniswelten. Insbesondere um Text in Blöcken z.B. nebeneinander darzustellen oder Bilder/Videos responsive einzubinden, was mit reinem html sehr umständlich ist.

**Comment by ChristopherDosin** [comment]
Hey @CMS-F - We're working on a version 2 that provides the CMS Designer for the blog detail view within the admin. So basically what you're looking for. However: We do not have an exact release date yet.
